#!/bin/bash -x
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --partition short
#SBATCH --account p324XX
#SBATCH --time 0:20:00
#SBATCH --mem 5G
#SBATCH --output generation.o
#SBATCH --job-name generation

module purge
module load mpi/openmpi-4.1.1-gcc.10.2.0 gcc/11.2.0 hdf5/1.10.8-openmpi-3.1.3-gcc-8.4.0 

mpirun -np 1 /home/ampXXXX/lammps2022Apr/build_quartic/lmp -i generation.inp  -log generation.log > generation.screen